fix: prevent action from running forever on success

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -36,5 +36,23 @@ runs:
       shell: bash
 
     - name: Run project.
-      run: cargo shuttle run
+      run: cargo shuttle run &
+      shell: bash
+
+    - name: Check for server start
+      run: |
+        echo "Waiting for server to start..."
+        timeout=60 # Timeout after 90 seconds
+        interval=5 # Check every 5 seconds
+        elapsed=0
+
+        while ! curl --silent --fail localhost:8000; do
+          sleep $interval
+          elapsed=$((elapsed + interval))
+          if [ $elapsed -ge $timeout ]; then
+            echo "Server failed to start within $timeout seconds."
+            exit 1
+          fi
+        done
+        echo "Server is up and running."
       shell: bash
